name: academic_check
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # 👉 GENERADOR DE ICONOS (AGREGADO)
  flutter_launcher_icons: ^0.13.1

flutter:

  # 👉 ICONOS MATERIAL DESIGN
  uses-material-design: true

  # 👉 ASSETS (tu icono personalizado)
  assets:
    - assets/icon/

# ==================================================
# 🔥 CONFIGURACIÓN DEL ICONO DE LA APP
# ==================================================
flutter_launcher_icons:
  android: true
  ios: true

  # 👉 ruta correcta según tu proyecto
  image_path: "assets/icon/icon.png"

  # opcional (mejor calidad en Android 12+)
  adaptive_icon_background: "#023052"
  adaptive_icon_foreground: "assets/icon/icon.png"